### ISSUE TITLE
links to delta3d.org are outdated

### ISSUE THREAD

**Issue by bradh** [delta3d/delta3d#1]
Looks like the domain has been repurposed....

**Comment by Gloomshroud** [comment]
Aye, no way to view documentation. A shame. Delta3D was a familiar face for a long time. :( Had a good wiki on the site.

**Comment by DieSlower** [comment]
Just FYI, you can get some of the archived tutorials here:
http://web.archive.org/web/20151110020709/http://delta3d.org/article.php?story=20050720155458456&topic=tutorials

**Comment by DieSlower** [comment]
And here:
http://web.archive.org/web/20100731072251/http://sourceforge.net/apps/mediawiki/delta3d/index.php?title=Tutorials

**Comment by projeto-arcanjo** [comment]
Are this project dead?

**Comment by yuxiangyu** [comment]
I have the same question

**Comment by LEgregius** [comment]
All of the engineers working were on it are now working on other things. It hasn't had any serious updates since 2016.  In order to continue the project, it would need a dependency overhaul because, perhaps with the vulkan rewrite of Open Scene Graph, and some updates of other dependencies.  CEGUI hasn't been updated in a while either. 

The delta3d.org website had a hosting issue where the person handling the hosting let the domain and hosting contract lapse by presumably by mistake, and attempts to recover it weren't successful.  We tried to rebuild the site on another domain name in 2016, but there were issue with the data backups and no one had the time then to try to spend the time to fix it.

**Comment by icemagno** [comment]
Don't forget the HLA is now "Evolved". You can try the PorticoRTI project. It is free.

**Comment by yuxiangyu** [comment]
Dose delta3d has any relation with another project simdisk https://github.com/USNavalResearchLaboratory/simdissdk ?
