### ISSUE TITLE
What is the purpose of physicscompiler on a high level ? 

### ISSUE THREAD

**Issue by sparshpriyadarshi** [delta3d/delta3d#4]
Code seems to suggest it attaches material information to the geodes of the input mesh.

What info does the DTPHYS file contain ?
This isn't supposed to modify the mesh(IVE) right ?

**Comment by LEgregius** [comment]
The material information is encoded in the mesh by the artist creating it. The physics compiler really just takes an a scene and generates a compiled set of non-convex objects that a separated by physics material. The physics materials can then be defined in the configuration of dtPhysics so that they have specific friction and other properties.  The dtPhys file is all of these annotated meshes as a simple set of vertices.

**Comment by sparshpriyadarshi** [comment]
I see, thank you for the clarification.
